# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function(v) {
    .Call(`_RHD_test`, v)
}

f_nd <- function(tGrid) {
    .Call(`_RHD_f_nd`, tGrid)
}

f_nd_each <- function(t) {
    .Call(`_RHD_f_nd_each`, t)
}

IQRout <- function(x, f) {
    .Call(`_RHD_IQRout`, x, f)
}

IQRout_vec <- function(x, f_vec) {
    .Call(`_RHD_IQRout_vec`, x, f_vec)
}

rank_rcpp <- function(x, ties) {
    .Call(`_RHD_rank_rcpp`, x, ties)
}

Xsim <- function(n, ev, ef, xi_type = 1L, nu_xi = 1) {
    .Call(`_RHD_Xsim`, n, ev, ef, xi_type, nu_xi)
}

Xout <- function(n0, tGrid, eta, type) {
    .Call(`_RHD_Xout`, n0, tGrid, eta, type)
}

Xout_all <- function(n0, tGrid, eta) {
    .Call(`_RHD_Xout_all`, n0, tGrid, eta)
}

FPCA <- function(X, tGrid, fve = 0.95) {
    .Call(`_RHD_FPCA`, X, tGrid, fve)
}

RKHS <- function(ev, J_vec, M = 1000L) {
    .Call(`_RHD_RKHS`, ev, J_vec, M)
}

sort_cpp <- function(x) {
    .Call(`_RHD_sort_cpp`, x)
}

RHD_inner <- function(x, X, tGrid, ev, ef, ld_mat, J_vec, f_iqr_vec, M_vec, M_type = 0L, ties = "min", out_type = 1L, num_M = 100L, stt = 0L) {
    .Call(`_RHD_RHD_inner`, x, X, tGrid, ev, ef, ld_mat, J_vec, f_iqr_vec, M_vec, M_type, ties, out_type, num_M, stt)
}

RHD_inner_prob <- function(x, X, tGrid, ev, ef, p_vec, J_vec, f_iqr_vec, M_vec, ties = "min", out_type = 1L, num_M = 100L, stt = 0L) {
    .Call(`_RHD_RHD_inner_prob`, x, X, tGrid, ev, ef, p_vec, J_vec, f_iqr_vec, M_vec, ties, out_type, num_M, stt)
}

RHDonly <- function(x, X, tGrid, ev, ef, ld_mat, J_vec, M_vec, M_type = 0L, ties = "min", num_M = 100L, stt = 0L) {
    .Call(`_RHD_RHDonly`, x, X, tGrid, ev, ef, ld_mat, J_vec, M_vec, M_type, ties, num_M, stt)
}

RHDonly_prob <- function(x, X, tGrid, ev, ef, p_vec, J_vec, M_vec, ties = "min", num_M = 100L, stt = 0L) {
    .Call(`_RHD_RHDonly_prob`, x, X, tGrid, ev, ef, p_vec, J_vec, M_vec, ties, num_M, stt)
}

MC1nd <- function(nX, nY, tGrid, ev, ef, ld_mat, J_vec, M_vec, M_type = 0L, ties = "min") {
    .Call(`_RHD_MC1nd`, nX, nY, tGrid, ev, ef, ld_mat, J_vec, M_vec, M_type, ties)
}

MC1nd_prob <- function(nX, nY, tGrid, ev, ef, prob_vec, J_vec, M_vec, M_type = 0L, ties = "min") {
    .Call(`_RHD_MC1nd_prob`, nX, nY, tGrid, ev, ef, prob_vec, J_vec, M_vec, M_type, ties)
}

MC2one <- function(n, n_out, tGrid, ev, ef, ld_mat, J_vec, M_vec, M_type = 0L, ties = "min") {
    .Call(`_RHD_MC2one`, n, n_out, tGrid, ev, ef, ld_mat, J_vec, M_vec, M_type, ties)
}

MC2one_prob <- function(n, n_out, tGrid, ev, ef, prob_vec, J_vec, M_vec, M_type = 0L, ties = "min") {
    .Call(`_RHD_MC2one_prob`, n, n_out, tGrid, ev, ef, prob_vec, J_vec, M_vec, M_type, ties)
}

Fadj_inner <- function(nSim, covMat, tGrid, ld_mat, J_vec, f_iqr_vec, M_vec, M_type = 0L) {
    .Call(`_RHD_Fadj_inner`, nSim, covMat, tGrid, ld_mat, J_vec, f_iqr_vec, M_vec, M_type)
}

Fadj <- function(M_adj, nSim, covMat, tGrid, ld_mat, J_vec, f_iqr_vec, M_vec, M_type = 0L, num_M = 100L, stt = 0L) {
    .Call(`_RHD_Fadj`, M_adj, nSim, covMat, tGrid, ld_mat, J_vec, f_iqr_vec, M_vec, M_type, num_M, stt)
}

Fadj_inner_prob <- function(nSim, covMat, tGrid, prob_vec, J_vec, f_iqr_vec, M_vec) {
    .Call(`_RHD_Fadj_inner_prob`, nSim, covMat, tGrid, prob_vec, J_vec, f_iqr_vec, M_vec)
}

Fadj_prob <- function(M_adj, nSim, covMat, tGrid, prob_vec, J_vec, f_iqr_vec, M_vec, num_M = 100L) {
    .Call(`_RHD_Fadj_prob`, M_adj, nSim, covMat, tGrid, prob_vec, J_vec, f_iqr_vec, M_vec, num_M)
}

